config/routes.rb
Myapp::Application.routes.draw do

  match 'teaching_staffs/new',:to=>'teaching_staffs#new'  
  resources :course_pricings
  resources :teaching_staffs
  resources :tax_rates
  match '/rate' => 'rater#create', :as => 'rate'

  resources :coupons do
    collection do
      get 'test'
      get 'apply'
      get 'redeem'
    end
  end
  resources :contacts
  resources :faqs
  resources :blogs
  resources :tags
  resources :courses 
  
  match 'payments/course_payment_gateway',:to=>'payments#course_payment_gateway'
  match 'payments/course_payment',:to=>'payments#course_payment'
  match 'payments/follow_course',:to=>'payments#follow_course'
  match 'payments/confirm_course_payment',:to=>'payments#confirm_course_payment'
  match "/download_pdf(.:format)" => "payments#invoice_pdf", :method => :get, :as=>:invoice_pdf
 
  resources :topics
  resources :tutorials
  resources :groups
  resources :under_constructions
  resources :o_classes
  resources :course_previews
  
  authenticated :user do
    root :to => 'screens#home'
  end
  root :to => 'screens#home'
  match '/about', :to => 'screens#about'
  match '/privacy', :to => 'screens#privacy'
  match '/terms', :to => 'screens#terms'
  match '/knowledge_partners', :to => 'screens#knowledge_partners'
  match '/user_reviews', :to => 'screens#user_reviews'

  #match '/contact', :to => 'screens#contact'
  #match '/faq', :to => 'screens#faq'
  match '/construction', :to => 'screens#construction'  
  match '/manage_courses', :to => 'courses#manage_courses'
  match '/upcomming_courses', :to => 'courses#upcomming_courses' 
  match '/popular_courses', :to => 'courses#popular_courses'  
  match '/datewise_courses', :to => 'courses#datewise_courses'
  match '/subscribed_courses', :to => 'courses#subscribed_courses'
  match '/course_status_search', :to => 'courses#course_status_search'
  match '/completed_courses', :to => 'courses#completed_courses'

  match '/updatecompleted_details', :to => 'courses#updatecompleted_details'
  match '/conclude_course', :to =>'courses#conclude_course'
  match '/concluded_course_update', :to=> 'courses#concluded_course_update'
  match '/concluded_courses', :to=> 'courses#concluded_courses'
  match '/edit_concluded_course', :to=> 'courses#edit_concluded_course'
  match '/update_un_concluded_course', :to=> 'courses#update_un_concluded_course'
  match '/interested_users', :to=> 'users#interested_users'

  devise_for :users, :controllers => {:registrations => "registrations",:sessions => "sessions"}

  devise_scope :user do
    match '/user_image', :to => 'registrations#user_image' 
  end
  
  resources :users
  match '/auth/:provider/callback' => 'authentication#create'
  resources :comments, :path_prefix => '/:commentable_type/:commentable_id'
  match '/my_courses', :to => 'courses#my_courses'  
  match '/show_image/:id', :to => 'courses#show_image' 
  match '/background_image/:id', :to => 'courses#background_image' 
  
#  match '*a', :to => 'home#routing_error'

  devise_scope :user do
    match '/sign_out', :to => 'sessions#destroy'
  end
end

app/models/faq.rb
# == Schema Information
#
# Table name: faqs
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  order_id   :integer
#  question   :text
#  answer     :text
#

class Faq < ActiveRecord::Base
  attr_accessible :question, :answer, :order_id
  default_scope order: 'faqs.order_id ASC'
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_filter :signed_in_admin_user, only: [:create, :edit,:update,:delete]
  def index
    @faqs = Faq.all
  end

  def show
    @faq = Faq.find(params[:id])
  end

  def new
    @faq = Faq.new
  end

  def create
    @faq = Faq.new(params[:faq])
    if @faq.save
      redirect_to faqs_path, :notice => "Successfully created faq."
    else
      render :action => 'new'
    end
  end

  def edit
    @faq = Faq.find(params[:id])
  end

  def update
    @faq = Faq.find(params[:id])
    if @faq.update_attributes(params[:faq])
      flash[:success] = "Successfully updated faq."
      redirect_to faqs_path, :notice  => "Successfully updated faq."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @faq = Faq.find(params[:id])
    @faq.destroy
    redirect_to faqs_url, :notice => "Successfully destroyed faq."
  end
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/views/faqs/_form.html.erb
<%= form_for @faq do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <p>
    <%= f.label :question %><br />
    <%= f.text_field :question %>
  </p>
  <p>
    <%= f.label :answer %><br />
    <%= f.text_field :answer %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/faqs/edit.html.erb
<% provide(:title, 'Edit Faqs') %>


<%= render 'form' %>

<p>
  <%= link_to "Show", @faq %> |
  <%= link_to "View All", faqs_path %>
</p>

app/views/faqs/index.html.erb
<% provide(:title, 'Frequently Asked Questions') %>
<% provide(:effectingHeader, 'Yes') %>
<div class="navbar navbar-fixed-top ds-dragover-1" >
     <div class="navbar-inner">
        <div class="container">
          <!-- <a class="brand" href=""><strong class="curr">SmartCoach</strong></a> -->
          <%= link_to "SmartCoach", root_path, class: "curr brand" %>
            <div class="navbar-content-1">
              

              <ul class="nav pull-right">
                <!-- <li class="active"> -->
               <li>
               
                  <%= link_to "Home", root_path %>
                </li>
                <li>
                  <%= link_to "About", about_path %>
                </li>
                
                <li class="active">
                  <%= link_to "Faq", faqs_path %>
                </li>
                <% if signed_in? %>
                  
                  <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <%= gravatar_for_with_size current_user, "15x15" %> <%= current_user.name %>  <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu" id="droplinks">
                  <li><%= link_to "Profile", current_user %></li>
                  <li class="divider"></li>
                  <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                  </ul>
                  </li>
                <% else %>
                  <li><%= link_to "Sign in", signin_path %></li>
                  <li>
                          <%= link_to "Subscribe", signup_path %>
                      </li>
                <% end %>
              </ul>
          </div>
        </div>
    </div>
</div>
<center>
  <div class="row">
    <div class="container">

      <div class="row">
        <ul class="nav nav-pills .pull-right">
          <li>
            <%= link_to "Courses", courses_path %>
          </li>
          <li><%= link_to "Tutorials", tutorials_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Online Classes", o_classes_path %></li>
          <% end %>
          <li><%= link_to "Blog", blogs_path %></li>
           <li ><%= link_to "Coaches", users_path %></li>
        </ul>
      </div>
      
      <div class="span12">
        
        <div id="faqs">
          <h2>General FAQs</h2>
          <% for faq in @faqs %>
              <div id="question" align="left">
                  <i class="icon-question-sign icon-white"></i>
                  <span><%= faq.question %></span>
              </div>
              <div id="answer" align="left">
                  <i class="icon-bullhorn icon-black"></i>
                  <span><%= faq.answer %></span>
                  <% if signed_in? && current_user.user_type == 3 #Admin %>
                    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_faq_path(faq), :class => 'btn btn-mini' %>
                     <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      faq_path(faq),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
                  <% end %>
              </div>

              <div class="clearfix"></div>
          <% end %>
        </div><!-- <div id="faqs"> -->
        <p class="text-info">Note: Click on the question to view its answer.</p>
      </div><!-- <div id="span12"> -->
    </div><!-- <div id="container"> -->
  </div><!-- <div id="row"> -->
  
</center>

app/views/faqs/new.html.erb
<% provide(:title, 'Crete Faqs') %>

<%= render 'form' %>

<p><%= link_to "Back to List", faqs_path %></p>

app/views/faqs/show.html.erb
<% provide(:title, 'Show Faqs') %>

<p>
  <strong>Question:</strong>
  <%= @faq.question %>
</p>
<p>
  <strong>Answer:</strong>
  <%= @faq.answer %>
</p>

<p>
  <%= link_to "Edit", edit_faq_path(@faq) %> |
  <%= link_to "Destroy", @faq, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", faqs_path %>
</p>