config/routes.rb
Myapp::Application.routes.draw do

  match 'teaching_staffs/new',:to=>'teaching_staffs#new'  
  resources :course_pricings
  resources :teaching_staffs
  resources :tax_rates
  match '/rate' => 'rater#create', :as => 'rate'

  resources :coupons do
    collection do
      get 'test'
      get 'apply'
      get 'redeem'
    end
  end
  resources :contacts
  resources :faqs
  resources :blogs
  resources :tags
  resources :courses 
  
  match 'payments/course_payment_gateway',:to=>'payments#course_payment_gateway'
  match 'payments/course_payment',:to=>'payments#course_payment'
  match 'payments/follow_course',:to=>'payments#follow_course'
  match 'payments/confirm_course_payment',:to=>'payments#confirm_course_payment'
  match "/download_pdf(.:format)" => "payments#invoice_pdf", :method => :get, :as=>:invoice_pdf
 
  resources :topics
  resources :tutorials
  resources :groups
  resources :under_constructions
  resources :o_classes
  resources :course_previews
  
  authenticated :user do
    root :to => 'screens#home'
  end
  root :to => 'screens#home'
  match '/about', :to => 'screens#about'
  match '/privacy', :to => 'screens#privacy'
  match '/terms', :to => 'screens#terms'
  match '/knowledge_partners', :to => 'screens#knowledge_partners'
  match '/user_reviews', :to => 'screens#user_reviews'

  #match '/contact', :to => 'screens#contact'
  #match '/faq', :to => 'screens#faq'
  match '/construction', :to => 'screens#construction'  
  match '/manage_courses', :to => 'courses#manage_courses'
  match '/upcomming_courses', :to => 'courses#upcomming_courses' 
  match '/popular_courses', :to => 'courses#popular_courses'  
  match '/datewise_courses', :to => 'courses#datewise_courses'
  match '/subscribed_courses', :to => 'courses#subscribed_courses'
  match '/course_status_search', :to => 'courses#course_status_search'
  match '/completed_courses', :to => 'courses#completed_courses'

  match '/updatecompleted_details', :to => 'courses#updatecompleted_details'
  match '/conclude_course', :to =>'courses#conclude_course'
  match '/concluded_course_update', :to=> 'courses#concluded_course_update'
  match '/concluded_courses', :to=> 'courses#concluded_courses'
  match '/edit_concluded_course', :to=> 'courses#edit_concluded_course'
  match '/update_un_concluded_course', :to=> 'courses#update_un_concluded_course'
  match '/interested_users', :to=> 'users#interested_users'

  devise_for :users, :controllers => {:registrations => "registrations",:sessions => "sessions"}

  devise_scope :user do
    match '/user_image', :to => 'registrations#user_image' 
  end
  
  resources :users
  match '/auth/:provider/callback' => 'authentication#create'
  resources :comments, :path_prefix => '/:commentable_type/:commentable_id'
  match '/my_courses', :to => 'courses#my_courses'  
  match '/show_image/:id', :to => 'courses#show_image' 
  match '/background_image/:id', :to => 'courses#background_image' 
  
#  match '*a', :to => 'home#routing_error'

  devise_scope :user do
    match '/sign_out', :to => 'sessions#destroy'
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def index
    @groups = Group.order(:name)
  end

  def show
    @group = Group.find(params[:id])
    @countTutorialsPerPage = 5
    @tutorials_for_group = @group.tutorials.paginate(page: params[:page], per_page: 5)
    @groups = Group.order(:name)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(params[:group])
    if @group.save
      redirect_to tutorials_path, notice: "Successfully created group."
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      redirect_to @group, notice: "Successfully updated group."
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_url, notice: "Successfully destroyed group."
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                groups_path, :class => 'btn' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/groups/index.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.id, group_path(group) %></td>
        <td><%= group.name %></td>
        <td><%=l group.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_group_path(group), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      group_path(group),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_group_path,
            :class => 'btn btn-primary' %>

app/views/groups/new.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/groups/show.html.erb
<% provide(:title, 'Tutorials for ' + @group.name) %>
<%- model_class = Group -%>
<div class="container">

  <div class="row">
        <ul class="nav nav-pills .pull-right">
          <li>
            <%= link_to "Courses", courses_path %>
          </li>
          <li class="active"><%= link_to "Tutorials", tutorials_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Online Classes", o_classes_path %></li>
          <% end %>
          <li><%= link_to "Blog", blogs_path %></li>
           <li ><%= link_to "Coaches", users_path %></li>
        </ul>
      </div>

  <div class="page-header">
    <% @groupStructure = @group.name + " ( #{@group.tutorials.where(ispublished: 1).size} )" %>
    <h3>Tutorials related to category: <%= @groupStructure %></h3>
  </div>
  <% if signed_in? && current_user.user_type == 3 #Admin %>
    <div class="form-actions">
      <%= link_to t('.back', :default => t("helpers.links.back")),
                  tutorials_path, :class => 'btn'  %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_group_path(@group), :class => 'btn' %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  group_path(@group),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' %>
    </div>
  <% end %>
  
  
  <div class="row">
        <div class="span8">
            
            <% if @group.tutorials.where(ispublished: 1).size >= 1 %>
                <div class="well">
                    <% if signed_in? && current_user.user_type == 1 #Teacher %>
                      <p><%= link_to "Add New Tutorial", new_tutorial_path , class: "move-to-right-top"%></p>
                    <% end %>
                    
                    <%= render @group.tutorials.where(ispublished: 1) %>

                    <% @group.tutorials.each do |tutorial| %>
                      <% if ((tutorial.id % @countTutorialsPerPage) == 0 ) %>
                        <% if signed_in? && current_user.user_type == 1 #Teacher %>
                          <p><%= link_to "Add New Tutorial", new_tutorial_path , class: "move-to-right-bottom"%></p>
                        <% end %>
                      <% end %>
                    <% end %>
                    
                    <div class="clearfix"></div>
                </div>
            <% else %>
                <div class="alert alert-alert">
                  No Tutorial in this category yet!!!!
                </div>
            <% end %>
        </div><!-- <div class="span8"> -->

        <div class="span3">
            <div class="">

               <!--  <form class="navbar-search pull-left">
                  <input type="text" class="search-query" placeholder="Search">
                </form>
                <div class="clearfix"></div> -->

                <div class="tabbable"> <!-- Only required for left/right tabs -->
                  <ul class="nav nav-tabs">
                    <li class="active"><a href="#categories" data-toggle="tab">Categories</a></li>
                    <li><a href="#upcomingcourses" data-toggle="tab">Upcoming Tutorials</a></li>
                  </ul>
                  <div class="tab-content">

                    <div class="tab-pane active" id="categories">
                      
                      <div class="categories">
                          
                          <ul class="nav nav-list">
                              <li class="nav-header"></li>
                              <li><%= link_to "All" + " ( #{Tutorial.where(ispublished: 1).all.size} )", tutorials_path %></a></li>
                              <% @groups.each do |group| %>
                                
                                <% if group.id == @group.id %>
                                  <% @groupStructure = group.name + " ( #{ group.tutorials.where(ispublished: 1).size } )" %>
                                  <li class="active"><a href="#"><%= link_to @groupStructure, group %></a></li>
                                <% else %>
                                  <% @groupStructure = group.name + " ( #{ group.tutorials.where(ispublished: 1).size } )" %>
                                  <li><a href="#"><%= link_to @groupStructure, group %></a></li>
                                <% end %>
                              <% end %>
                          </ul>
                          <br/>
                        
                          <% if signed_in? && current_user.user_type == 3 #Admin %>
                            <%= link_to "Manage Category", groups_path, class: "btn btn-info" %>
                          <% end %>
                      </div>

                    </div><!-- <div class="tab-pane active" id="categories"> -->

                    <div class="tab-pane" id="upcomingcourses">
                      
                      <div class="upcoming">
                          <% Tutorial.where(ispublished: 0).all.each do |t| %>
                              <div class="upcoming-widget">
                                <div class="widget-thumbnail">
                                  <!-- <img src="homeOnline.jpg" width="70px" height="100px"> -->
                                  <!--#link_to image_tag("homeOnline.jpg", border 0), {action: '#', controller: '#'},class: '#'-->
                                  <%= link_to image_tag("#{t.image}", border: 0, width: "50", height: "50")%>
                                </div><!-- end .widget-thumbnail -->
                                <div class="widget-body">
                                  <h4><%= t.title %></h4>
                                  <span class="label label-info"><%= t.releasemonth %></span>
                                </div>
                                <div class="clearfix"></div>
                              </div>
                          <% end %>
                      </div>
                    </div><!-- <div class="tab-pane" id="categories"> -->
                  
                  </div><!--<div class="tab-content"> -->
                </div><!-- Only required for left/right tabs -->

                
          </div>
        </div><!-- <div class="span3"> -->
      </div><!-- <div class="row"> -->

</div>