config/routes.rb
Myapp::Application.routes.draw do

  match 'teaching_staffs/new',:to=>'teaching_staffs#new'  
  resources :course_pricings
  resources :teaching_staffs
  resources :tax_rates
  match '/rate' => 'rater#create', :as => 'rate'

  resources :coupons do
    collection do
      get 'test'
      get 'apply'
      get 'redeem'
    end
  end
  resources :contacts
  resources :faqs
  resources :blogs
  resources :tags
  resources :courses 
  
  match 'payments/course_payment_gateway',:to=>'payments#course_payment_gateway'
  match 'payments/course_payment',:to=>'payments#course_payment'
  match 'payments/follow_course',:to=>'payments#follow_course'
  match 'payments/confirm_course_payment',:to=>'payments#confirm_course_payment'
  match "/download_pdf(.:format)" => "payments#invoice_pdf", :method => :get, :as=>:invoice_pdf
 
  resources :topics
  resources :tutorials
  resources :groups
  resources :under_constructions
  resources :o_classes
  resources :course_previews
  
  authenticated :user do
    root :to => 'screens#home'
  end
  root :to => 'screens#home'
  match '/about', :to => 'screens#about'
  match '/privacy', :to => 'screens#privacy'
  match '/terms', :to => 'screens#terms'
  match '/knowledge_partners', :to => 'screens#knowledge_partners'
  match '/user_reviews', :to => 'screens#user_reviews'

  #match '/contact', :to => 'screens#contact'
  #match '/faq', :to => 'screens#faq'
  match '/construction', :to => 'screens#construction'  
  match '/manage_courses', :to => 'courses#manage_courses'
  match '/upcomming_courses', :to => 'courses#upcomming_courses' 
  match '/popular_courses', :to => 'courses#popular_courses'  
  match '/datewise_courses', :to => 'courses#datewise_courses'
  match '/subscribed_courses', :to => 'courses#subscribed_courses'
  match '/course_status_search', :to => 'courses#course_status_search'
  match '/completed_courses', :to => 'courses#completed_courses'

  match '/updatecompleted_details', :to => 'courses#updatecompleted_details'
  match '/conclude_course', :to =>'courses#conclude_course'
  match '/concluded_course_update', :to=> 'courses#concluded_course_update'
  match '/concluded_courses', :to=> 'courses#concluded_courses'
  match '/edit_concluded_course', :to=> 'courses#edit_concluded_course'
  match '/update_un_concluded_course', :to=> 'courses#update_un_concluded_course'
  match '/interested_users', :to=> 'users#interested_users'

  devise_for :users, :controllers => {:registrations => "registrations",:sessions => "sessions"}

  devise_scope :user do
    match '/user_image', :to => 'registrations#user_image' 
  end
  
  resources :users
  match '/auth/:provider/callback' => 'authentication#create'
  resources :comments, :path_prefix => '/:commentable_type/:commentable_id'
  match '/my_courses', :to => 'courses#my_courses'  
  match '/show_image/:id', :to => 'courses#show_image' 
  match '/background_image/:id', :to => 'courses#background_image' 
  
#  match '*a', :to => 'home#routing_error'

  devise_scope :user do
    match '/sign_out', :to => 'sessions#destroy'
  end
end

app/views/shared/_author_info.html.erb
<div class="aboutauthor">
  <div class="container ">
    <h1>About the Author</h1>
    <% @authors.each do |author|%>
    <div class="row" style="width:30%; display:inline-block; clear:left; margin:15px">

      <div class="authorimage">
        <% if author.user.image_blob == nil %>
        <% if author.user.omni_image_url == nil %>
        <%= gravatar_for_with_size author, "100x100" %>
        <% else  %>
        <%= image_tag(author.user.omni_image_url,size: "100x100", alt: "")%>
        <% end  %>
        <% else  %>
        <%= image_tag url_for(:controller => 'registrations',:action => 'user_image', :id => author.user.id), :size => "100x100" %>
        <% end  %>
      </div>
      <div class="authorinfo">

        <h4><%= author.name %></h4>
        <p><%= author.description%></p>

      </div>
      <div class="container clearfix"></div>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_course_detial.html.erb
 
<% if @course.background_image ==nil %>
<div class="coursedetailtop" style="background-color: #d14836;background-image: -webkit-linear-gradient(top,#2C3E50,#ECF0F1); background-image: -moz-linear-gradient(top,#2C3E50,#ECF0F1);  background-image: -ms-linear-gradient(top,#2C3E50,#ECF0F1);  background-image: -o-linear-gradient(top,#2C3E50,#ECF0F1);  background-image: linear-gradient(top,#2C3E50,#ECF0F1);  color:#fff;  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#2C3E50', endColorstr='#ECF0F1'); 
" id="top">
<% else %>
<div class="coursedetailtop" style="background-image: url('<%= url_for(:controller=>"courses", :action => 'background_image', :id => @course.id) %>');" id="top">
<% end %>

  <div class="container">
    <div class="row">
      <div class="span4">
        <div class="coursevideo">
          
         
        </div>
      </div>
      <div class="span7">
        <div class="coursedesc">
          <div class="coursetitle">
            <h3><%= @course.title %></h3>
          </div>
          <div class="subtitle">
            <h4><%= @course.short_desc %></h4>
          </div>
          <div class="subtitle" style="color:#fcff00">
            <% if @course.is_coming_soon %>
            <h4>Date to be announced</h4>
            <% else %>
            <% start=""
              if @course.start_date != nil 
                start=@course.start_date.to_formatted_s(:long)
              end
              duration=""
              if @course.start_date != nil and @course.end_date != nil 
                x=(@course.end_date - @course.start_date).to_i
                y=x/7
                z=x%7
                duration = pluralize(y,"Week") 
                if(z != 0) 
                  duration = duration + " " + pluralize(z,"Day") 
                end
                duration = duration + " Long"
                #duration=distance_of_time_in_words(@course.start_date,@course.end_date)
              end
              next_session=""
              if @course.start_date != nil and @course.end_date != nil 
                next_session="Next Session: #{start} (#{duration})"
              end
             %>
            <h4><%= next_session %></h4>
            <% end %>
            <% if @price.to_i != 0 %>
            <h2 style="color:white">Rs&nbsp;<%= @price.to_i %></h2>
            <% end %>
          </div>
          <div class="container clearfix"></div>
          <div class="subsection">

            <% if (current_user.present? ) %>
              <% if !(current_user.has_role? :admin) %>

                <% if @course.is_coming_soon %>
                <% if @status!="follow" %>

                  <%= link_to "Follow",payments_follow_course_path(:id=>@course.id),  :class=>"enroll" %>
                  <% end %>
                <% elsif @status=="enroll" %>
                <a href="<%= lms_course_url("#{@course.lms_id}modules")%>"><div class="enroll">Go To Class
                </div></a>
                <% elsif @status=="completed" %>
                
                <% else %>
                  <%= link_to "enroll",payments_course_payment_path(:id=>@course.id),  :class=>"enroll" %>
                <% end %> 

              <% end %> 

            <% else %>
              <% if @course.is_coming_soon %>
                <%= link_to "Follow",payments_follow_course_path(:id=>@course.id),  :class=>"enroll" %>
              <!--  <a href="#loginmodal" role="button" data-toggle="modal" class="enroll">Follow</a> -->
              
              <% else %>
               <%= link_to "enroll",payments_course_payment_path(:id=>@course.id),  :class=>"enroll" %>
              <!-- <a href="#loginmodal" role="button" data-toggle="modal" class="enroll">Enroll</a> -->

              <% end %> 
            <% end %> 

            <a href="#previewcourse"><div class="shortlist">
              Preview
            </div></a>

          </div>
          <div class="clearfix"></div>
          <div style="margin-left: 80px;">
           <a>
            <%#= link_to image_tag("#{@course.image}", border: 0, width: "100", height: "100")%> 
            <% unless url_for(:only_path => true, :overwrite_params=> { }) == '/courses?'  %>
            <br align = "center">
            <% end %>
            <%= rating_for @course, "rate"  %>
            <div id="rating" style="color:#fff;"><%= pluralize(@qty,"Rate") if !!@qty%></div>
            <% unless url_for(:only_path => true, :overwrite_params=> { }) == '/courses?'  %>
           </a>
            <div style="height:40px;"><%= image_tag "group.png" if @subscribers_count >= 1 %><b class="learners_count"><%= pluralize(@subscribers_count, "Learner") if @subscribers_count >= 1%> </b> </div>

           <% end %>
          </a>
        </div>
      </div>
      <div class="container clearfix"></div>
    </div>
  </div>
  <div class="container clearfix">

  </div>
</div>

<div class="container clearfix">
</div>
</div>

app/views/shared/_course_header.html.erb
 <div class="clearfix"></div>
 <div class="pagehead separation">
  <div class="container">   
   <h1 style="  color: #28468D;font-size:30px;font-family: sans-serif;font-weight: normal;">Discover Courses</h1>
 </div>
</div> 
<div class="container categorygap"> 
  <div class="row">
    <div class="span12 courselibsectioninfo">
      <div class="courselibsectioninfo">
        <div class="coursecount pull-left">
          <span class="badge badge-info">Found <%=pluralize(@total_course_count,"Course")%> </span>
        </div>
        <ul class="nav pull-right" style="margin-left:20px;">
         <li id="fat-menu" class="dropdown" >
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" style=" font-size: 1.2em;
          position: relative;color:black; ">Sort By&nbsp;&nbsp;<b class="caret" style="margin-top:1px;border-left: 7px solid transparent;border-right: 7px solid transparent;border-top: 7px solid #34495E;"></b></a>
          
          <ul class="dropdown-menu">
            
           <li><%= link_to "Date" + " ( #{Course.where(ispublished: 1,:isconcluded=>false).order(:created_at).size} )", datewise_courses_path %></li>
           <li><%= link_to "Upcoming" + " ( #{Course.where(ispublished: 0, :isconcluded=>false).all.size} )", upcomming_courses_path %></li>
           <li><%= link_to "Popularity" + " ( #{Course.where(ispopular: 1,ispublished: 1, :isconcluded=>false).size} )", popular_courses_path %></li>
           <li><%= link_to "Subscribed"+ " ( #{StudentCourse.where(:status =>"enroll").map(&:course_id).uniq.size} )", subscribed_courses_path %></li> 
           <li><%= link_to "Default" + " ( #{Course.where(ispublished: 1,:isconcluded=>false).size} )", courses_path %></li>
           
         </ul>
       </li>
     </ul>

     <ul class="nav pull-right">
       <li id="fat-menu" class="dropdown" style="color:black;">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" style=" font-size: 1.2em;
        position: relative;color:black; ">Categories&nbsp;<b class="caret" style="margin-top:1px;border-left: 7px solid transparent;border-right: 7px solid transparent;border-top: 7px solid #34495E;"></b></a>
        <ul class="dropdown-menu">

          <li><%= link_to "All" + " ( #{Course.where(ispublished: 1, :isconcluded=>false).all.size} )", courses_path %></li>


          <% @topics.each do |topic| %>   
          <% @topicStructure = topic.name + " ( #{ topic.courses.where(ispublished: 1, :isconcluded=>false).size} )" %>

          <li><%= link_to @topicStructure, topic %></li>
          <%end%>    
        </ul>
      </li>
    </ul>
    <div class="clearfix"></div>
    
    
  </div>
  <div class="clearfix"></div>

app/views/shared/_course_preview.html.erb
<div class="previewcourse" id="previewcourse">
  <div class="container">
    <div class="row">
      <h2>Lecture Preview: A Sneak Peak into the course</h2>
      <% a=0 %>
      <% @course.course_previews.where(enable: 1).order(:sequence).each do |p| %>
      <% a +=1  %>
      <div class="span6 prevbox">
       <table> <tr>
         <td>
           <div class="bannervideo">
            <% url = p.video_url.split('/')  %>
            <a href="#preview_model<%= a %>" data-toggle="modal" > <img src="http://i.ytimg.com/vi/<%= url[4] %>/default.jpg" /></a>
            <div id="preview_model<%= a %>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><%=image_tag("close.png", alt: "")%></a></button>
              <div class="modal-header">
                <h3 id="myModalLabel">Preview Video</h3>
              </div>
              <div class="modal-body">
               <iframe width="400" height="350" src=<%= p.video_url %> frameborder="0" allowfullscreen class="iframe"></iframe> 
             </div>
           </div>
         </div>
       </td>
       <td>
         <div class="previnfo">
           <h3><%= p.name %></h3>
           <p class="prevtxt"><%= p.desc %></p>
         </div>
       </td>
     </tr>
   </table>
 </div>
 <% end %>  
</div>
</div>
</div>

app/views/shared/_course_reviews.html.erb
<div class="coursereviews">
  <div class="container">
    <div class="row">
      <div align="center">
        <h3><%=@course.comments.size%> Reviews</h3>
        <br/>
      </div>
    </div>
    <%= render "comments" %>
    <div class="container clearfix"></div>
  </div>
  <div class='apple_pagination' >
   <%= will_paginate @comments, :container => false %>
 </div>
 <div class="container clearfix"></div>
 <div class="row">
  <div align="center">
    <div >
      <%= link_to "Add Reveiw",new_comment_path(:commentable=>@course,:commentable_type=>"course"), :locals => {:commentable => @course},class:"browsemore" %>
    </div>
  </div>
</div>
</div>

app/views/shared/_courselist.html.erb
<div class="container courseclub" >
  <div class="row">
    
    <% @courses.each do |course|%>
    <div class="span7">
      <div class="courses">
                 <article class="course path-100" data-connection="18 20" data-tag="ruby-basics" id="course-6">
          <div class="card-a course-inner">
            <div class="course-progress" data-width="0%" style="width: 0%;"></div>
            <% if course.data!=nil %>
            <%= image_tag url_for(:controller => 'courses',:action => 'show_image', :id => course.id), width: "130", height: "130",:class=>"course-badge img-circle" %>
            <% else %>
            <%= image_tag "test.png", width: "130", height: "130",:class=>"course-badge img-circle" %>
            <% end %>
            <% if course.is_coming_soon %>
              <div class="coming_soon"><%= image_tag("coming_soon.png") %></div>
            <% elsif price_of_course_according_to_date(course).to_i ==0 %>
              <div class="free"><%= image_tag("free.png") %></div>
            <% end %>
      
            <div class="course-content">
              <em class="label-a label-offset" <%= course.topic.color==nil ? "style=background-color:#2b6341" : "style=background-color:#{course.topic.color}" %> rel="tooltip" data-original-title="Orientation courses are entry-level courses in each of our Paths."> <b><%=course.topic.name.split(' ').map(&:capitalize).join(' ') if !course.topic.nil? %></b></em>
            
              <!-- <em class="label-b">Free Course</em> -->

              <%=link_to(course) do %><h3 class="course-name"><%= course.title.split(' ').map(&:capitalize).join(' ') %></h3>
              <p class="course-desc"><%= course.short_desc  %></p>
              <%end%></div>

            </div>
          </article>
        </div>

      </div>
      <%end%>
      
    </div>
  </div>
  

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
<div class="alert alert-error">
The form contains <%= pluralize(object.errors.count, "error") %>.
</div>
<ul>
	<% if object.errors.full_messages == "Sequence can't be blank" %>
	<%= "Display order cannot be blank" %>
	<% else %>
<% object.errors.full_messages.each do |msg| %>
<li>* <%= msg %></li>
<% end %>
<% end %>
</ul>
</div>
<% end %>

app/views/shared/_media_reviews.html.erb
<!-- <div class="ourknowledgepartners secondary-content">
  <div class="container" align="center">
   <div class="row testimonial">
      <h2 style="color: #757474;">Featured In</h2>

      <div class="listofkp" >
        <img src="assets/featured.png" />
      </div>

    </div>
  </div>
</div> -->

app/views/shared/_side_menu.html.erb
   <script type="text/javascript">

   $(function(){
    // this will get the full URL at the address bar
    var url = window.location.href; 

    // passes on every "a" tag 
    $("#side_menu a").each(function() {
            // checks if its the same on the address bar
            if(url == (this.href)) { 
            	$(this).closest("a").addClass("active");
            }
          });
  });
   </script>

   <div>
   	<ul id="side_menu">
   		<li><%= link_to "Users", users_path %></li>   		 		
   		<li><%= link_to "New Course Library", new_course_path %></li>
   		<li><%= link_to "Manage Course Library", manage_courses_path %></li>
   		<li><%= link_to "New Category",new_topic_path %> </li>
   		<li><%= link_to "Manage Category", topics_path %></li>  		
   		<li><%= link_to "New Preview",new_course_preview_path %></li>
   		<li><%= link_to "Manage Preview",course_previews_path %></li>
      <li><%= link_to "New Coupon", new_coupon_path %></li>
   		<li><%= link_to "Manage Coupon", coupons_path %></li>
      <li><%= link_to "New Course Price",new_course_pricing_path %></li>   		
   	  <li><%= link_to "Manage Course Price",course_pricings_path %></li>
   		<li><%= link_to "Create Tax", new_tax_rate_path %></li>
      <li><%= link_to "Manage Taxes",tax_rates_path %></li>

      <li><%= link_to "New Teacher", new_teaching_staff_path %></li>
      <li><%= link_to "Manage Teaching Staff",teaching_staffs_path %></li>   
      <li><%= link_to "Course Status Search",course_status_search_path %></li>  
      <li><%= link_to "Conclude Course", conclude_course_path %></li>
      <li><%= link_to "Interested Users", interested_users_path %></li>
   	</ul>   	
   </div>