config/routes.rb
Myapp::Application.routes.draw do

  match 'teaching_staffs/new',:to=>'teaching_staffs#new'  
  resources :course_pricings
  resources :teaching_staffs
  resources :tax_rates
  match '/rate' => 'rater#create', :as => 'rate'

  resources :coupons do
    collection do
      get 'test'
      get 'apply'
      get 'redeem'
    end
  end
  resources :contacts
  resources :faqs
  resources :blogs
  resources :tags
  resources :courses 
  
  match 'payments/course_payment_gateway',:to=>'payments#course_payment_gateway'
  match 'payments/course_payment',:to=>'payments#course_payment'
  match 'payments/follow_course',:to=>'payments#follow_course'
  match 'payments/confirm_course_payment',:to=>'payments#confirm_course_payment'
  match "/download_pdf(.:format)" => "payments#invoice_pdf", :method => :get, :as=>:invoice_pdf
 
  resources :topics
  resources :tutorials
  resources :groups
  resources :under_constructions
  resources :o_classes
  resources :course_previews
  
  authenticated :user do
    root :to => 'screens#home'
  end
  root :to => 'screens#home'
  match '/about', :to => 'screens#about'
  match '/privacy', :to => 'screens#privacy'
  match '/terms', :to => 'screens#terms'
  match '/knowledge_partners', :to => 'screens#knowledge_partners'
  match '/user_reviews', :to => 'screens#user_reviews'

  #match '/contact', :to => 'screens#contact'
  #match '/faq', :to => 'screens#faq'
  match '/construction', :to => 'screens#construction'  
  match '/manage_courses', :to => 'courses#manage_courses'
  match '/upcomming_courses', :to => 'courses#upcomming_courses' 
  match '/popular_courses', :to => 'courses#popular_courses'  
  match '/datewise_courses', :to => 'courses#datewise_courses'
  match '/subscribed_courses', :to => 'courses#subscribed_courses'
  match '/course_status_search', :to => 'courses#course_status_search'
  match '/completed_courses', :to => 'courses#completed_courses'

  match '/updatecompleted_details', :to => 'courses#updatecompleted_details'
  match '/conclude_course', :to =>'courses#conclude_course'
  match '/concluded_course_update', :to=> 'courses#concluded_course_update'
  match '/concluded_courses', :to=> 'courses#concluded_courses'
  match '/edit_concluded_course', :to=> 'courses#edit_concluded_course'
  match '/update_un_concluded_course', :to=> 'courses#update_un_concluded_course'
  match '/interested_users', :to=> 'users#interested_users'

  devise_for :users, :controllers => {:registrations => "registrations",:sessions => "sessions"}

  devise_scope :user do
    match '/user_image', :to => 'registrations#user_image' 
  end
  
  resources :users
  match '/auth/:provider/callback' => 'authentication#create'
  resources :comments, :path_prefix => '/:commentable_type/:commentable_id'
  match '/my_courses', :to => 'courses#my_courses'  
  match '/show_image/:id', :to => 'courses#show_image' 
  match '/background_image/:id', :to => 'courses#background_image' 
  
#  match '*a', :to => 'home#routing_error'

  devise_scope :user do
    match '/sign_out', :to => 'sessions#destroy'
  end
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ActiveRecord::Base
	attr_accessible :name
  has_many :taggings
  has_many :blogs, through: :taggings


  def self.search(search)
  	if search
      find(:all, conditions: ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def index
    @tags = Tag.order(:name).search(params[:search])
  end

  def show
    @tag = Tag.find(params[:id])
    @countBlogsPerPage = 5
    #@courses_for_topic = @topic.courses.paginate(page: params[:page], per_page: 5)
    @blogs_for_tag = @tag.blogs.paginate(page: params[:page], per_page: 5)
    @tags = Tag.order(:name)
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(params[:tag])
    if @tag.save
      redirect_to tags_path, notice: "Successfully created tag."
    else
      render :new
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update_attributes(params[:tag])
      redirect_to @tag, notice: "Successfully updated tag."
    else
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_url, notice: "Successfully destroyed tag."
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for @tag, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tags_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tags/_tags.html.erb
<%- model_class = Tag -%>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= link_to tag.id, tag_path(tag) %></td>
        <td><%= tag.name %></td>
        <td><%=l tag.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_tag_path(tag), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      tag_path(tag),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tags/edit.html.erb
<%- model_class = Tag -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tags/index.html.erb
<%- model_class = Tag -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<%= form_tag tags_path, method: "get", id: "tags_search", html: { class: 'form-horizontal' } do %>
<p>
  <%= text_field_tag :search, params[:search], class: 'text_field'  %>
</p>
<p>
  <%= submit_tag "Search", name: nil, :class => 'btn btn-primary' %>
</p>
<div id="tags"><%= render 'tags' %></div>
<% end %>


<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tag_path,
            :class => 'btn btn-primary' %>

app/views/tags/index.js.erb
$('#tags').html("<%= escape_javascript(render("tags")) %>");

app/views/tags/new.html.erb
<%- model_class = Tag -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tags/show.html.erb
<% provide(:title, 'Blogs for ' + @tag.name) %>
<%- model_class = Tag -%>
<div class="container">

  <div class="row">
        <ul class="nav nav-pills .pull-right">
          <li>
            <%= link_to "Courses", courses_path %>
          </li>
          <li><%= link_to "Tutorials", tutorials_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Online Classes", o_classes_path %></li>
          <% end %>
          <li class="active"><%= link_to "Blog", blogs_path %></li>
           <li ><%= link_to "Coaches", users_path %></li>
        </ul>
      </div>

  <div class="page-header">
    <% @tagStructure = @tag.name + " ( #{@tag.blogs.where(ispublished: 1).size} )" %>
    <h3>blogs related to category: <%= @tagStructure %></h3>
  </div>
  <% if signed_in? && current_user.user_type == 3 #Admin %>
    <div class="form-actions">
      <%= link_to t('.back', :default => t("helpers.links.back")),
                  blogs_path, :class => 'btn'  %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_tag_path(@tag), :class => 'btn' %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  tag_path(@tag),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' %>
    </div>
  <% end %>
  
  
  <div class="row">
        <div class="span8">
            
            <% if @tag.blogs.where(ispublished: 1).size >= 1 %>
                <div class="well">
                    <% if signed_in? && current_user.user_type == 1 #Teacher %>
                      <p><%= link_to "Add New Blog", new_blog_path , class: "move-to-right-top"%></p>
                    <% end %>
                    
                    <%= render @tag.blogs.where(ispublished: 1) %>

                    <% @tag.blogs.each do |blog| %>
                      <% if ((blog.id % @countBlogsPerPage) == 0 ) %>
                        <% if signed_in? && current_user.user_type == 1 #Teacher %>
                          <p><%= link_to "Add New Blog", new_blog_path , class: "move-to-right-bottom"%></p>
                        <% end %>
                      <% end %>
                    <% end %>
                    
                    <div class="clearfix"></div>
                </div>
            <% else %>
                <div class="alert alert-alert">
                  No Blogs in this category yet!!!!
                </div>
            <% end %>
        </div><!-- <div class="span8"> -->

        <div class="span3">
            <div class="">

               <!--  <form class="navbar-search pull-left">
                  <input type="text" class="search-query" placeholder="Search">
                </form>
                <div class="clearfix"></div> -->

                <div class="tabbable"> <!-- Only required for left/right tabs -->
                  <ul class="nav nav-tabs">
                    <li class="active"><a href="#categories" data-toggle="tab">Categories</a></li>
                    <li><a href="#upcomingcourses" data-toggle="tab">Upcoming Blogs</a></li>
                  </ul>
                  <div class="tab-content">

                    <div class="tab-pane active" id="categories">
                      
                      <div class="categories">
                          
                          <ul class="nav nav-list">
                              <li class="nav-header"></li>
                              <li><%= link_to "All" + " ( #{Blog.where(ispublished: 1).all.size} )", blogs_path %></a></li>
                              <% @tags.each do |tag| %>
                                <% @tagStructure = tag.name + " ( #{tag.blogs.where(ispublished: 1).size } )" %>
                                <% if tag.id == @tag.id %>
                                  <li class="active"><a href="#"><%= link_to @tagStructure, tag %></a></li>
                                <% else %>
                                  <li><a href="#"><%= link_to @tagStructure, tag %></a></li>
                                <% end %>
                              <% end %>
                          </ul>
                          <br/>
                          
                          <% if signed_in? && current_user.user_type == 3 #Admin %>
                            <%= link_to "Manage Category", tags_path, class: "btn btn-info" %>
                          <% end %>
                      </div>

                    </div><!-- <div class="tab-pane active" id="categories"> -->

                    <div class="tab-pane" id="upcomingcourses">
                      
                      <div class="upcoming">
                          <% Blog.where(ispublished: 0).all.each do |t| %>
                              <div class="upcoming-widget">
                                <div class="widget-thumbnail">
                                  <!-- <img src="homeOnline.jpg" width="70px" height="100px"> -->
                                  <!--#link_to image_tag("homeOnline.jpg", border 0), {action: '#', controller: '#'},class: '#'-->
                                  <%= link_to image_tag("#{t.image}", border: 0, width: "50", height: "50")%>
                                </div><!-- end .widget-thumbnail -->
                                <div class="widget-body">
                                  <h4><%= t.title %></h4>
                                  <span class="label label-info"><%= t.releasemonth %></span>
                                </div>
                                <div class="clearfix"></div>
                              </div>
                          <% end %>
                      </div>
                    </div><!-- <div class="tab-pane" id="categories"> -->
                  
                  </div><!--<div class="tab-content"> -->
                </div><!-- Only required for left/right tabs -->

                
          </div>
        </div><!-- <div class="span3"> -->
      </div><!-- <div class="row"> -->

</div>